import { NodePlugin } from '@/types/node-plugin';
import { supabase } from '@/integrations/supabase/client';

export const capsuleCrmNode: NodePlugin = {
  type: 'capsule-crm',
  name: 'Capsule CRM',
  description: 'Customer relationship management with Capsule',
  category: 'action',
  icon: 'https://cdn.activepieces.com/pieces/capsule-crm.png',
  color: '#0D83DD',
  inputs: [
    {
      name: 'apiKey',
      label: 'API Token',
      type: 'text',
      required: true,
      description: 'Your Capsule CRM API token',
      isApiKey: true,
    },
    {
      name: 'action',
      label: 'Action',
      type: 'select',
      required: true,
      options: [
        { label: 'Create Contact', value: 'createContact' },
        { label: 'Update Contact', value: 'updateContact' },
        { label: 'Create Opportunity', value: 'createOpportunity' },
        { label: 'Create Project', value: 'createProject' },
        { label: 'Create Task', value: 'createTask' },
        { label: 'Update Opportunity', value: 'updateOpportunity' },
        { label: 'Add Note to Entity', value: 'addNoteToEntity' },
        { label: 'Find Contact', value: 'findContact' },
        { label: 'Find Project', value: 'findProject' },
        { label: 'Find Opportunity', value: 'findOpportunity' },
      ],
      description: 'Action to perform',
    },
    {
      name: 'firstName',
      label: 'First Name',
      type: 'text',
      required: false,
      description: 'Contact first name',
      showWhen: { field: 'action', values: ['createContact'] },
    },
    {
      name: 'lastName',
      label: 'Last Name',
      type: 'text',
      required: false,
      description: 'Contact last name',
      showWhen: { field: 'action', values: ['createContact'] },
    },
    {
      name: 'email',
      label: 'Email',
      type: 'text',
      required: false,
      description: 'Contact email address',
      showWhen: { field: 'action', values: ['createContact', 'updateContact', 'findContact'] },
    },
    {
      name: 'contactId',
      label: 'Contact ID',
      type: 'text',
      required: false,
      description: 'Contact ID to update',
      showWhen: { field: 'action', values: ['updateContact'] },
    },
    {
      name: 'opportunityName',
      label: 'Opportunity Name',
      type: 'text',
      required: false,
      description: 'Name of the opportunity',
      showWhen: { field: 'action', values: ['createOpportunity', 'findOpportunity'] },
    },
    {
      name: 'opportunityId',
      label: 'Opportunity ID',
      type: 'text',
      required: false,
      description: 'Opportunity ID to update',
      showWhen: { field: 'action', values: ['updateOpportunity'] },
    },
    {
      name: 'value',
      label: 'Value',
      type: 'number',
      required: false,
      description: 'Opportunity value',
      showWhen: { field: 'action', values: ['createOpportunity', 'updateOpportunity'] },
    },
    {
      name: 'projectName',
      label: 'Project Name',
      type: 'text',
      required: false,
      description: 'Name of the project',
      showWhen: { field: 'action', values: ['createProject', 'findProject'] },
    },
    {
      name: 'taskDescription',
      label: 'Task Description',
      type: 'textarea',
      required: false,
      description: 'Task description',
      showWhen: { field: 'action', values: ['createTask'] },
    },
    {
      name: 'dueDate',
      label: 'Due Date',
      type: 'text',
      required: false,
      description: 'Task due date (YYYY-MM-DD format)',
      placeholder: '2024-12-31',
      showWhen: { field: 'action', values: ['createTask'] },
    },
    {
      name: 'entityType',
      label: 'Entity Type',
      type: 'select',
      required: false,
      options: [
        { label: 'Contact', value: 'contact' },
        { label: 'Opportunity', value: 'opportunity' },
        { label: 'Project', value: 'project' },
      ],
      description: 'Type of entity to add note to',
      showWhen: { field: 'action', values: ['addNoteToEntity'] },
    },
    {
      name: 'entityId',
      label: 'Entity ID',
      type: 'text',
      required: false,
      description: 'ID of the entity',
      showWhen: { field: 'action', values: ['addNoteToEntity'] },
    },
    {
      name: 'note',
      label: 'Note',
      type: 'textarea',
      required: false,
      description: 'Note content',
      showWhen: { field: 'action', values: ['addNoteToEntity'] },
    },
  ],
  outputs: [
    {
      name: 'result',
      type: 'object',
      description: 'Capsule CRM API response',
    },
  ],
  async execute(inputs) {
    const { data, error } = await supabase.functions.invoke('capsule-crm-action', {
      body: inputs,
    });

    if (error) throw error;
    return { result: data };
  },
};
