-- Insert 6 new integration records for the new nodes
INSERT INTO integrations (integration_id, name, description, "LongDescription", category, icon, provider, version, requires_installation, is_completed, is_enabled, is_integrated, priority, flow_builder_instructions, installation_config)
VALUES 
(
  'bettermode',
  'Bettermode',
  '<p>Bettermode is a community platform that helps you build, manage, and grow engaged communities. Create spaces, manage members, and foster meaningful interactions.</p>',
  '<p>Maximize Bettermode''s capabilities with Rantir, seamlessly integrating it with other Community apps and over 1000 additional services. Streamline community management, automate member engagement, and track community growth across multiple platforms. Build customizable and scalable workflows between Bettermode and your existing tools.</p>',
  'community',
  'https://cdn.prod.website-files.com/67e18b84fa43974c4775c6ac/67f05c8c087a298922c12808_677c7f49d6983ea31655da5a_672ef7f96514a9b7cadf54f4_bettermode.svg',
  'rantir',
  '1.0.0',
  true,
  false,
  false,
  false,
  0,
  '{}',
  '{}'
),
(
  'bika',
  'Bika',
  '<p>Bika is an AI-powered automation platform that helps you create and manage intelligent workflows. Trigger AI agents, automate tasks, and connect multiple services seamlessly.</p>',
  '<p>Maximize Bika''s capabilities with Rantir by integrating it with compatible Automation and AI applications. Streamline workflow automation, trigger intelligent agents, and orchestrate complex processes across multiple platforms. Create flexible and scalable AI-powered workflows between Bika and your existing technology stack.</p>',
  'automation',
  'https://cdn.prod.website-files.com/67e18b84fa43974c4775c6ac/67f05c8c087a298922c12808_677c7f49d6983ea31655da5a_672ef7f96514a9b7cadf54f4_bika.svg',
  'rantir',
  '1.0.0',
  true,
  false,
  false,
  false,
  0,
  '{}',
  '{}'
),
(
  'binance',
  'Binance',
  '<p>Binance is a leading cryptocurrency exchange platform. Access real-time market data, trading pairs, account information, and blockchain analytics through the Binance API.</p>',
  '<p>Maximize Binance''s capabilities with Rantir, seamlessly integrating it with other Financial and Analytics apps. Access cryptocurrency prices, trading data, and account information to build automated trading strategies, portfolio tracking, and market analysis workflows across multiple platforms.</p>',
  'finance',
  'https://cdn.prod.website-files.com/67e18b84fa43974c4775c6ac/67f05c8c087a298922c12808_677c7f49d6983ea31655da5a_672ef7f96514a9b7cadf54f4_binance.svg',
  'rantir',
  '1.0.0',
  true,
  false,
  false,
  false,
  0,
  '{}',
  '{}'
),
(
  'blockscout',
  'Blockscout',
  '<p>Blockscout is a blockchain explorer that provides detailed information about transactions, addresses, tokens, and blocks across multiple blockchain networks.</p>',
  '<p>Maximize Blockscout''s capabilities with Rantir by integrating it with compatible Blockchain and Analytics applications. Query blockchain data, track transactions, monitor addresses, and analyze on-chain activity across Ethereum, Polygon, Optimism, and other networks. Build transparent and scalable blockchain workflows.</p>',
  'blockchain',
  'https://cdn.prod.website-files.com/67e18b84fa43974c4775c6ac/67f05c8c087a298922c12808_677c7f49d6983ea31655da5a_672ef7f96514a9b7cadf54f4_blockscout.svg',
  'rantir',
  '1.0.0',
  true,
  false,
  false,
  false,
  0,
  '{}',
  '{}'
),
(
  'bluesky',
  'Bluesky',
  '<p>Bluesky is a decentralized social network protocol. Create posts, manage your profile, view your timeline, and engage with the decentralized social media ecosystem.</p>',
  '<p>Maximize Bluesky''s capabilities with Rantir, seamlessly integrating it with other Social Media apps and over 1000 additional services. Automate post scheduling, monitor engagement, manage your profile, and build cross-platform social media workflows. Experience decentralized social networking at scale.</p>',
  'social-media',
  'https://cdn.prod.website-files.com/67e18b84fa43974c4775c6ac/67f05c8c087a298922c12808_677c7f49d6983ea31655da5a_672ef7f96514a9b7cadf54f4_bluesky.svg',
  'rantir',
  '1.0.0',
  true,
  false,
  false,
  false,
  0,
  '{}',
  '{}'
),
(
  'bonjoro',
  'Bonjoro',
  '<p>Bonjoro is a video messaging platform that helps you send personalized video messages to customers, leads, and team members. Create tasks, manage contacts, and track video engagement.</p>',
  '<p>Maximize Bonjoro''s capabilities with Rantir by integrating it with compatible Marketing and CRM applications. Automate personalized video outreach, manage customer contacts, create follow-up tasks, and track video engagement across multiple platforms. Build scalable video marketing workflows.</p>',
  'marketing',
  'https://cdn.prod.website-files.com/67e18b84fa43974c4775c6ac/67f05c8c087a298922c12808_677c7f49d6983ea31655da5a_672ef7f96514a9b7cadf54f4_bonjoro.svg',
  'rantir',
  '1.0.0',
  true,
  false,
  false,
  false,
  0,
  '{}',
  '{}'
)
ON CONFLICT (integration_id) DO NOTHING;