INSERT INTO integrations (
  integration_id,
  name,
  description,
  icon,
  category,
  provider,
  version,
  node_type,
  requires_installation,
  is_enabled,
  is_completed,
  is_integrated,
  priority,
  LongDescription
) VALUES (
  'google-sheets',
  'Google Sheets',
  'Connect to Google Sheets to read, write, and manage spreadsheet data',
  'https://developers.google.com/sheets/api/images/sheets-icon.png',
  'Productivity',
  'Google',
  '1.0.0',
  'google-sheets',
  true,
  true,
  false,
  false,
  5,
  'Google Sheets integration allows you to perform comprehensive spreadsheet operations including reading data, inserting rows, updating cells, creating spreadsheets, managing worksheets, and more. Perfect for automating data workflows and connecting your applications to Google Sheets.'
) ON CONFLICT (integration_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  node_type = EXCLUDED.node_type,
  requires_installation = EXCLUDED.requires_installation,
  LongDescription = EXCLUDED.LongDescription;