import { NodePlugin } from '@/types/node-plugin';
import { supabase } from '@/integrations/supabase/client';

export const cambAiNode: NodePlugin = {
  type: 'camb-ai',
  name: 'Camb.ai',
  description: 'AI-powered conversation and content generation',
  category: 'action',
  icon: 'https://cdn.activepieces.com/pieces/camb-ai.png',
  color: '#8B5CF6',
  inputs: [
    {
      name: 'apiKey',
      label: 'API Key',
      type: 'text',
      required: true,
      description: 'Your Camb.ai API key',
      isApiKey: true,
    },
    {
      name: 'action',
      label: 'Action',
      type: 'select',
      required: true,
      options: [
        { label: 'Text to Sound', value: 'createTextToSound' },
        { label: 'Text to Speech', value: 'createTextToSpeech' },
        { label: 'Translation', value: 'createTranslation' },
        { label: 'Transcription', value: 'createTranscription' },
        { label: 'Custom API Call', value: 'createCustomApiCall' },
      ],
      description: 'Action to perform',
    },
    {
      name: 'text',
      label: 'Text',
      type: 'textarea',
      required: true,
      description: 'Text to convert',
      placeholder: 'Enter text to convert...',
      showWhen: { field: 'action', values: ['createTextToSound', 'createTextToSpeech', 'createTranslation'] },
    },
    {
      name: 'voice',
      label: 'Voice',
      type: 'select',
      required: false,
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Male', value: 'male' },
        { label: 'Female', value: 'female' },
      ],
      description: 'Voice type',
      showWhen: { field: 'action', values: ['createTextToSpeech'] },
    },
    {
      name: 'sourceLanguage',
      label: 'Source Language',
      type: 'select',
      required: true,
      options: [
        { label: 'English', value: '1' },
        { label: 'Spanish', value: '2' },
        { label: 'French', value: '3' },
        { label: 'German', value: '4' },
        { label: 'Italian', value: '5' },
        { label: 'Portuguese', value: '6' },
        { label: 'Chinese', value: '7' },
        { label: 'Japanese', value: '8' },
        { label: 'Korean', value: '9' },
        { label: 'Arabic', value: '10' },
        { label: 'Russian', value: '11' },
        { label: 'Hindi', value: '12' },
        { label: 'Dutch', value: '13' },
        { label: 'Swedish', value: '14' },
        { label: 'Turkish', value: '15' },
        { label: 'Polish', value: '16' },
        { label: 'Indonesian', value: '17' },
        { label: 'Thai', value: '18' },
        { label: 'Vietnamese', value: '19' },
        { label: 'Hebrew', value: '20' },
      ],
      description: 'Source language to translate from',
      showWhen: { field: 'action', values: ['createTranslation'] },
    },
    {
      name: 'targetLanguage',
      label: 'Target Language',
      type: 'select',
      required: true,
      options: [
        { label: 'English', value: '1' },
        { label: 'Spanish', value: '2' },
        { label: 'French', value: '3' },
        { label: 'German', value: '4' },
        { label: 'Italian', value: '5' },
        { label: 'Portuguese', value: '6' },
        { label: 'Chinese', value: '7' },
        { label: 'Japanese', value: '8' },
        { label: 'Korean', value: '9' },
        { label: 'Arabic', value: '10' },
        { label: 'Russian', value: '11' },
        { label: 'Hindi', value: '12' },
        { label: 'Dutch', value: '13' },
        { label: 'Swedish', value: '14' },
        { label: 'Turkish', value: '15' },
        { label: 'Polish', value: '16' },
        { label: 'Indonesian', value: '17' },
        { label: 'Thai', value: '18' },
        { label: 'Vietnamese', value: '19' },
        { label: 'Hebrew', value: '20' },
      ],
      description: 'Target language to translate to',
      showWhen: { field: 'action', values: ['createTranslation'] },
    },
    {
      name: 'audioUrl',
      label: 'Audio URL',
      type: 'text',
      required: false,
      description: 'URL of audio file to transcribe',
      showWhen: { field: 'action', values: ['createTranscription'] },
    },
    {
      name: 'endpoint',
      label: 'API Endpoint',
      type: 'text',
      required: false,
      description: 'Custom API endpoint path',
      showWhen: { field: 'action', values: ['createCustomApiCall'] },
    },
    {
      name: 'method',
      label: 'HTTP Method',
      type: 'select',
      required: false,
      default: 'GET',
      options: [
        { label: 'GET', value: 'GET' },
        { label: 'POST', value: 'POST' },
        { label: 'PUT', value: 'PUT' },
        { label: 'DELETE', value: 'DELETE' },
      ],
      description: 'HTTP method for custom API call',
      showWhen: { field: 'action', values: ['createCustomApiCall'] },
    },
    {
      name: 'body',
      label: 'Request Body',
      type: 'code',
      language: 'json',
      required: false,
      description: 'Request body (JSON format)',
      showWhen: { field: 'action', values: ['createCustomApiCall'] },
    },
  ],
  outputs: [
    {
      name: 'result',
      type: 'object',
      description: 'Camb.ai API response',
    },
  ],
  async execute(inputs) {
    const { data, error } = await supabase.functions.invoke('camb-ai-action', {
      body: inputs,
    });

    if (error) throw error;
    return { result: data };
  },
};
